### PR TITLE
Bug fix/hyd cond

### PR DESCRIPTION
**Pull request by martynpclark**
The code to compute hydraulic conductivity in macropores is
```
 if(volFracLiq > theta_mp)then
  theta_e       = (volFracLiq - theta_mp) / (theta_sat - theta_mp)
  hydCondMP_liq = (satHydCond_ma - satHydCond_mi) * (theta_e**mpExp)
 else
```
which means that the hydraulic conductivity for macropores will be negative if the conductivity for macropores is greater than for micropores.

The total hydraulic conductivity is
```
scalarHydCond   = hydCond_noIce*iceImpedeFac + scalarHydCondMP
```
and the total conductivity can be negative if there is substantial ice impedance.

It is a good idea to require that the conductivity for macropores be greater than for micropores.

### CODE REVIEW

**Comment by arbennett** [comment]
Could we simply set the conductivity to zero in this case?

**Comment by bartnijssen** [comment]
@arbennett : Which conductivity would be set to 0?

Wouldn't it be easier to set the `k_macropore` to `k_soil` if `k_macropore < k_soil` and issue a warning, just to make sure that the model continues. If we can modify the message to indicate what a user can do to fix this that may be helpful as well.

```
if(k_macropore(iLayer-nSnow) < k_soil(iLayer-nSnow))then
      k_macropore(iLayer-nSnow) = k_soil(iLayer-nSnow)
      message=trim(message)//"hydraulic conductivity for macropores is less than the hydraulic conductivity for micropores"
      err=20; return
     endif
```

**Comment by martynpclark** [comment]
@bartnijssen yes, this is a good idea. A better solution. It means that the model does not stop.

**Comment by arbennett** [comment]
Yeah, I agree, @bartnijssen that sounds like a good solution.

**Comment by andywood** [comment]
Yeah, that was my suggestion earlier too ...

**Comment by andywood** [comment]
I would also expand the message, to "hydraulic conductivity for macropores
(VALUE) is less than the hydraulic conductivity for micropores (VALUE):
resetting macropore conductivity to equal micropore value" and even give
the gru/hru id if that's handy in the routine.

**Review by arbennett — CHANGES_REQUESTED** [review]
It seems @andywood, @bartnijssen, and myself all would like to see the workaround so that this doesn't stop the simulation. I think what we really want to ensure is that at line 1031 of `soilLiqFlxf.90`:
```
scalarHydCond = max(hydCond_noIce*iceImpedeFac + scalarHydCondMP, 0.0_dp) # or maybe some tiny value
```

**Comment by martynpclark** [comment]
Implemented changes in a separate PR

**Pull request closed without merging**
